import fs from 'fs';

const rows = [
  [1, 'E-TIANA VENTURES LTD', '5, Bombay Crescent Apapa', 'Dr Martins E.Enebeli', '+234-8085288012, 234-8052880012, 234-8080218248, 234-8121158111', 'etianamarine@yahoo.com, etianamarine@gmail.com'],
  [2, 'YANNIS MARITIME SERVICES NIG LTD', '38 Bombay Crescent Apapa Lagos Nigeria', 'Ochuko Mr Abilo', '+234-8033017079,234-9090604732', 'abiloughe@yahoo.com, asabiscol@gmail.com'],
  [3, 'JESSCO MARITIME RESOURCE LTD', '19, Adele rd. Apapa Lagos', 'Mr Onojaife Kingsley', '+234803330492', ''],
  [4, 'MARK & FINAH NIG LTD', '13/15, Sapele rd. Apapa Lagos', 'Onumaegbu Chief Luck', '', ''],
  [5, 'SUNNY STAR MARINE SERVICES LTD', '33, Creek rd. Apapa Lagos', 'Sunny Thoms', '+2348033716027', 'supply@sunnystarmarineservices.com'],
  [6, 'LEBRADAN NIGERIAN LIMITED', '1A/1B Crowther Crescent Apapa GRA Lagos', 'NASIRU DANJUMA IBRAHIM', '+2347032038233 / +2348097531003', 'lebradan2@gmail.com / ibrodinho2007@gmail.com'],
  [7, 'KAZUMA SHIPPING', '10, Arodorome rd. Apapa Lagos', 'A.Okpo Mr. Sunny', '', ''],
  [8, 'DOMSUN INVESTMENT & MARINE SERVICES LTD', '10, Pelewura Way Apapa Lagos', 'Mr. D .T. Onabajo', '+234-8072111168, +234-8033049287', 'dimschandlers@yahoo.com, dimschandlers@gmail.com'],
  [9, 'BEHLISS -MEGA SUPPLY LTD', '21 WARE HOUSE ROAD APAPA', 'EDAFE NELSON OFUNAMA', '2348162223552', 'belismarineglobalsupply@gmail.com'],
  [10, 'PATRICK GANZA LIMITED', 'Suite 25, Anjorin Shopping Complex Apapa Lagos', 'Patrick Mr. Patrick', '', ''],
  [11, 'JET BLUE SERVICES LTD', 'ALHAJI MOSHOOD TIJANI ROAD OFF RANDLE VENUE APAPA LAGOS', 'KINGSLEY MADUKWE MADUKWE', '2348033443555', 'info@jetblue-services.com'],
  [12, 'SHOPWORKS LIMITED', '', '', '', ''],
  [13, 'S.ADISON LIMITED', '1, Sand Beach Coconut Apapa Lagos', 'Mr. Samuel Adindu Uwandu', '+234-8033824551. +234-8185440242', 'Uwandu.s@yahoo.com'],
  [14, "PRINCE DE MARITIME INT'L", 'Suite 8A, Amusement Park Plaza, Apapa Lagos', 'Uche Fidelis Akonye Mr. Prince', '+234-7030625949. +234-8187525274', 'Maritimeprince14@gmail.com, princedemaritime@yahoo.com'],
  [15, 'LUKSUMPTA INTERNATIONAL VENTURES', '23 Badagry Road of Marine Road', 'Mr Akpodeh Emoefe', '+234-8032716780, +234-7081035559', 'Luksumpta@yahoo.com'],
  [16, 'MERCYWELL MARITIME SERVICE LIMITED', '5 Mosco Road Abeokuta Express Ojokoro Lagos', 'Oluwafemi Mr. Ogundeyi', '', ''],
  [17, 'TORRO ENTERPRISES LTD', '', '', '', ''],
  [18, 'E.O.FABUNMI&SONS LTD', '', '', '', ''],
  [19, 'ZAMLAK NIG LTD', '', '', '', ''],
  [20, 'GLUTFIELD NIG. LTD', '', '', '', ''],
  [21, 'SOUTHEAST ATLANTIC LTD', '', '', '', ''],
  [22, 'ADAGOS NI SERVICES', '', '', '', ''],
  [23, 'MOUGAUNI VENTURES LTD', '', '', '', ''],
  [24, 'THE TWIN BROTHERS NIG LTD', '', '', '', ''],
  [25, 'C & RESOURCES LTD', '', '', '', ''],
  [26, 'GEO REYSTING PRODUCT LTD', '', '', '', ''],
  [27, "D'ZENIA SOLUTIONS LTD", '', '', '', ''],
  [28, 'ATLAMART SERVICES LTD', '', '', '', ''],
  [29, 'VOW VENTURES LTD', '', '', '', ''],
  [30, 'HARRIBOND RESOURCES LTD', '', '', '', ''],
  [31, 'VEGGIE SUPPLY ENTERPRISES', '', '', '', ''],
  [32, 'ALHAJA AMINU & SONS', '', '', '', ''],
  [33, 'OBISCO NIG LTD', '', '', '', ''],
  [34, 'FORTUNE GLOBAL SHIPPING LOGISTICS LTD', '', '', '', ''],
  [35, 'SIMEON A. SHARMAH LTD', '', '', '', ''],
  [36, 'OCEANSTAR GLOBAL', '', '', '', ''],
  [37, 'ELIJOD MARITIME LTD', '', '', '', ''],
  [38, 'COLLOSAL EXPRESSO LTD', '', '', '', ''],
  [39, 'SEAL ATLANTIC LIMITED', '', '', '', ''],
  [40, 'KEVIN GLOBAL MARINE SERVICES', '', '', '', ''],
  [41, 'ELIROSE NIG. LTD', '', '', '', ''],
  [42, 'CHI-WHITE ENT. NIG. LTD', '', '', '', ''],
  [43, 'CHUKS NIG ENTERPRISES', '', '', '', ''],
  [44, 'LABAMBA INTEGRATED SERVICES', '', '', '', ''],
  [45, 'CHALYVIS INTL LTD', '', '', '', ''],
  [46, "SMITHCO INT'L. GLOBAL RESOURCES LTD", '', '', '', ''],
  [47, 'ABBERBEEN NIG LTD', '', '', '', ''],
  [48, 'JIMITEX & PARTNER LTD', '', '', '', ''],
  [49, 'J C maritime inter Ltd', '', '', '', ''],
  [50, 'UCHE JOSIAH & SON VENTURES', '', '', '', ''],
  [51, 'EAST WEST COAST NIG LTD', '', '', '', ''],
  [52, 'ONYEMA CHIMA & SONS ENTERPRISES LTD', '', '', '', ''],
  [53, 'ROCK MARINE INTL.', '', '', '', ''],
  [54, 'OCEAN-WAVE LOGISTICS SERVICES LTD', '', '', '', ''],
  [55, 'TOBANCO NIG. LTD.', '', '', '', ''],
  [56, 'VICMATTI MSK LTD', '', '', '', ''],
  [57, "CLIFF'S PRIDE RESOURCES INVESTMENT LTD", '', '', '', ''],
  [58, 'EDE EBGUABA & SONS LTD', '', '', '', ''],
  [59, 'PAT CYRIL COMPANY', '', '', '', ''],
  [60, 'ALLIED CONTINENTAL SERVICES LTD', '', '', '', ''],
  [61, 'KEZINTIA SERVICES LTD', '', '', '', ''],
  [62, 'VIENTOR VENTURES LTD', '', '', '', ''],
  [63, 'HANNADI NIGERIA LIMITED', '', '', '', ''],
  [64, 'CHOBEN-OPS LTD', '', '', '', ''],
  [65, 'VALGO MEDIA LTD', '', '', '', ''],
  [66, 'JOSI MARITIME LIMITED', '', '', '', ''],
  [67, 'JERRI-JO GLOBAL CONCEPT NIG. LTD', '', '', '', ''],
  [68, 'PEG BOYE COMPANY', '', '', '', ''],
  [69, 'HASSANDI NIG LTD', '', '', '', ''],
  [70, 'BAOTA INT. AGENCIES NIG LTD', '', '', '', ''],
  [71, 'OLAMACKISM NIG LTD', '', '', '', ''],
  [72, 'EBENEZER LOGISTICS & MARINE SERVICES LTD', '', '', '', ''],
  [73, 'BOLRON GLOBAL SERVICES', '', '', '', ''],
  [74, 'UFERE UDE VENTURES', '', '', '', ''],
  [75, 'DOLPHIN CHANDLER ENTERPRISES', '', '', '', ''],
  [76, 'EZESON COMPANY NIG LTD.', '', '', '', ''],
  [77, 'HERITAGE MARINE RESOURCES LTD', '', '', '', ''],
  [78, 'WORLD OVERCOMER INTL. RECONCILATION FORUM', '', '', '', ''],
  [79, "CHALOKAS INT'L LTD", '', '', '', ''],
  [80, 'SKIVAM NIG. LTD', 'block 133 plot 14 lekki epe expressway lekki Lagos', 'kingsley fufeyin', '', ''],
  [81, 'EJIX MARITIME LTD.', '', '', '', ''],
  [82, "MGB INT'L LTD", '', '', '', ''],
  [83, 'ARSENAL MARINE VENTURES', '', '', '', ''],
  [84, 'MANUEL AUDREY SERVICES NIG. LTD', '', '', '', ''],
  [85, 'AFRICAN CONTINENTAL MARITIME LTD.', '', '', '', ''],
  [86, "VICTOR INT'L SERVICES", '', '', '', ''],
  [87, 'BMW ADESINA NIG. LTD.', '', '', '', ''],
  [88, 'LADY BOLA INVESTMENT LTD', '', '', '', ''],
  [89, 'KENNY AGENCIES NIG. LTD.', '', '', '', ''],
  [91, 'ASHEDUKUM & SONS NIG. LTD.', '', '', '', ''],
  [92, 'RIGORS ENTERPRISES', '', '', '', ''],
  [93, 'ELITO NIGERIA LTD.', '', '', '', ''],
  [94, 'TJAFRIOR COMPANY', '', '', '', ''],
  [95, 'JETARE NIGERIA LTD.', '', '', '', ''],
  [96, 'GHAREJE NIGERIA LTD', '', '', '', ''],
  [97, 'OTENS GLOBAL ENTERPRISES', '', '', '', ''],
  [98, "JOET ERU'S INT'L LTD.", '', '', '', ''],
  [99, 'FAST FOCUS SERVICES NIG LTD', '', '', '', ''],
  [100, 'TAMASI MARINE & INDUSTRIAL VENTURES LTD', '', '', '', ''],
  [101, 'ALIPEP NIG. LTD', '', '', '', ''],
  [102, 'DE-KAIBIRI NIG. LTD', '', '', '', ''],
  [103, 'ENO GENERAL AGENCIES NIG. LTD.', '', '', '', ''],
  [104, 'EMMAJA & SONS COMPANY', '', '', '', ''],
  [105, 'GFMC NIGERIA LIMITED', '', '', '', ''],
  [106, 'ATI-BEN COMPANY NIG.', '', '', '', ''],
  [107, 'P.UTECH', '', '', '', ''],
  [108, 'DAKIMOLA BROTHERS LTD.', '', '', '', ''],
  [109, 'CHUGOS & SONS ENTERPRISES', '', '', '', ''],
  [110, 'JOHN MORNRAIN LTD.', '', '', '', ''],
  [111, 'JEK & SONS LTD', '', '', '', ''],
  [112, 'ANDY TRANSACTIONS', '', '', '', ''],
  [113, 'DE KAILO OIL SERVICES LTD.', '', '', '', ''],
  [114, 'BENTON GLOBAL RESOURCES LTD', '', '', '', ''],
  [115, 'Rang Technical services Ltd', '21 Afam Street D/Line,opus plaza port Harcourt Nigeria', 'Duran Duran', '234-08037076961', 'rangeshipsuppliers@yahoo.com'],
  [116, 'ROSELINK COMPANY LTD', '', '', '', ''],
  [117, 'OSCAR INTEGRATED SERVICES', '', '', '', ''],
  [118, 'AZOBEMOR SHIP CHANDLERS', '', '', '', ''],
  [119, 'SEASHOR OFFSHORE CONTRACTING CO. LTD.', '', '', '', ''],
  [120, 'SHORE TIDE NIG', '', '', '', ''],
  [122, 'REBECCA NIG LTD', '', '', '', ''],
  [123, 'HEPA GLOBAL ENERGY LTD', '', '', '', ''],
  [124, 'IKOKO & SONS', '', '', '', ''],
  [125, "CHALYVIS INT'L LTD", '', '', '', ''],
  [126, 'JACK MARINE INT,L SERVICES LTD', '73A MARINE ROAD APAPA LAGOS', 'AKPUNA godfrey', '', ''],
  [127, 'ALBRAL ALLIANCE LTD', '3 WOSU AVENUE,IGBO ETCHE RD RUMUOKWURUSHI PORT HARCOURT RIVER STATE', 'PURGATORIO RACHEL ONU', '234-8149577734', 'info@albralliance.com'],
  [128, 'CLEARLINK SERVICES NIGERIA LIMITED', '6 kofo Abayomi street, APAPA,lAGOS', 'CHUCKS CELESTINE EFUNWA', '', ''],
  [129, 'PIDMARITIME SERVICES NIG LTD', '33 CREEK ROAD APAPA LAGOS', 'INNOCENT DANSU POSU', '', ''],
  [130, 'IVANNA GLOBAL SUPPLIES LIMITED', '8 WHARE HOUSE ROAD APAPA', 'COSMAS OSE EBOSELE', '234-8035294563', 'info@ivannaglobal.com'],
  [131, 'EASYSHOP EASYCOOK SERVICES LTD', '1 PETER AYANSI CLOSE SURULERE LAGOS', 'SAUDAT OLADEINDE SALAMI', '', ''],
  [132, 'GSHOPPERS GLOBAL SERVICES LTD', 'NO 101 G,U AKEH RD ELIOZU PORT-HARCOURT', 'CHIOKE FAVOUR', '', ''],
  [133, 'FLOUSHO NIGERIA LIMITED', '68 BORNO CRESCENT APAPA LAGOS NIGERIA', 'FLORENCE ADEYANJU', '2348033053665', 'floshoning@yahoo.com'],
  [134, 'LUBARI MARITIME COMPANY LTD', '21ROAD WCLOSE PLOT24B FESTAC LAGOS', 'SIEDOMA DUMKA', '2348033412596,2347049469437', 'contact@lubarigroup.com'],
  [135, 'PHILMARIO GLOBAL SERVICES LTD', '11B QUEENS BARRACK RD APAPA', 'EBOSELE PHILLIP OSEMHANRE', '2348056544164,2348169224603', 'info@philmarioglobalservices.com'],
  [136, 'KING SHIPPING TRADING SERVICES LTD', '3MOSHOOD TIJANI STREET APAPA LAGOS', 'CHUKWUMA HYACENT', '2348167069828', 'info@kingshippingtrading.com'],
  [137, 'PERKRA ENERGY LTD', 'OVAMANN HOUSE,1 SHALOM STREET,OFF APPLE JUNCTION ,ALONG OKOTA LINK ROAD,AMUWO ODOFIN LAGOS', 'MUDIAGA OMOROKO', '', ''],
  [138, 'NELSHORE RESOURCES LTD', 'NO 39 RAILWAY ROAD BY PLATEUS STREET APAPA LAGOS', 'OLUWAFEMI,PHILLIP [JITADE', '2347064696999', 'nelshoreresources@gmail.com'],
  [139, 'ALPHOKING LTD', '45 Bombay crescent Apapa Lagos', 'Matthew Iwuchukwu', '', ''],
  [140, 'SPARKLE SUPPLY CHAIN LTD', '40 IDI STREET OLODI APAPA', 'OBASUYI MARGARETH', '2348056801081', 'sparklesupplychainltd@gmail.com'],
  [141, 'ROUND EDGE LIMITED', 'Mobolaji Johnson Estate Lekki phase 1-Lagos', 'ELUEMUNOR KEVIN', '2348077757557,2348099577770', 'roundedgelimited@yahoo.com'],
  [142, 'HENDIAC NIG LTD', '71A MARINE RD APAPA LAGOSW', 'OKOGBO HENRY', '2347063907461', 'hendiacnigltd@gmail.com'],
  [143, 'VISHPRO LOGISTIC LTD', '302A,MURTALA MOHAMMED WAY, YABA LAGOS', 'HEART SUNDAY IGBEDION', '', ''],
  [144, 'ANGO YAKUBU UMAR LTD', 'N R C Q MARINE BEACH BUS STOP APAPA', 'ANGO YAKUBU', '2348039421333', 'angoyakubu@gmail.com'],
  [145, 'MAYSTAR MARINE SERVICES', 'BLOCK', 'ADADOKUN SUNDAY OLALERE', '', ''],
  [146, 'BENUELSON SERVICE LTD', '8 ALHAJI KADIRI STREET OFF SUNRISE BUS STOP APAPA LAGOS', 'OLESHE BENJAMIN', '2348111103057', 'benuelsonservice@yahoo.com'],
  [147, 'ROHWA MARINE LTD', '1 COMMECIAL ROAD APAPA', 'ONOMEREGWAE DEGAULLE JOHNSON', '', ''],
  [148, 'WESTERN CHANDLERS LTD', '103,TAFAWA BALEWA CR, OFF ADENIRAN OGUNSANYA SURULERE', 'AKINDEJOYE GBEMISOLA DAMILOLA', '', ''],
  [149, 'MODOIL AND GAS LTD', '10 AFOLABI AWOSANYA STREET IKEJA', 'OMODELE ADEBOLA OYEBANJI', '2347032824993,2349095415474', 'omodeleadebola@hotmail.com'],
  [150, 'NOBLE KINGS GLOBAL OCEAN LTD', '7/8 HAEEB BUILDING OSHODI EXPRESS WAY COCONUT', 'EGEJURU CHIAGOROM NOBLE', '2348136597780,2347065967632', 'noblekingsglobaloceanltd@gmaiil.com'],
  [151, 'RITZY MARINE SERVICES NIG LTD', '7 LADIPO STREET OLODI APAPA LAGOS', 'RICHARD EKWERE', '', ''],
  [152, 'FACMARIN GLOBAL SERVICES LTD', '31 APAPA OSHODI EXPRESS WAY BY COMFORT HOTEL LAGS', 'ACHILIKE FRANCIS CHIBUIKE', '2347062031531', 'facmarin.op@gmail.com'],
  [153, 'TDE GLOBAL SERVICES LTTD', 'N0 30 PLOT 35, COMMERCIAL ROAD,RAIKWAY LINE,APAPA', 'OYEKU BABATUNDE MURITALA', '234703332001', 'tdemarineservices@gmail.com'],
  [154, 'BALLOCOAST VENTURE LIMITED', '42 RANDLE ROAD APAPA', 'SHERIFF BALOGUN', '2348034176928', 'supply.ballocoast@gmail.com'],
  [155, 'PROACTIVE SHPPING LTD', '8B BADAGRY ROAD GRA APAPA', 'AGHA IKENNA COLLINS', '2349060007626', 'info@proactive-shipping.com'],
  [156, 'GLOBAL AQUATIC CONCEPT LIMITED', '24/25 CREEK ROAD APAPA', 'AVIME OHN RENE', '2348100811955,2348021426077', 'info@globalaquaticlimited.com'],
  [157, 'BROOK OFFSHORE LIMITED', '1 OCEANS DRIVE OBIRI IKWERE JUNCTION NTA RD OZUOBA PORT HARCOURT', 'ONYEMA ABIODUN VICTORIA', '2348180471414', 'brookoffshorelimited@yahoo.com'],
  [158, 'ADE&ADE SUPPLY SERVICE', '9 RANDLE ROAD APAPA LAGOS STATE', 'OPEYEMI ADESUGBA', '2349155236944', 'adesupply680@gmail.com'],
  [159, 'FAVIGRA LOGISTICS SERVICES ENT.LTD', 'BLOCK 3 FLAT 5, MILLENNIUM EST,VICTOR ODUGUWA STREET AMUWO ODOFIN LAGOS', 'WILCOX ANDREW DIEPIRINYE', '2347086869798', 'favigralogistics@gmail.com'],
  [160, 'ALPHA - GREEN LOGISTIC CO,INT;L LTD', '35 GRAFEM AVENUE RUMUKRUSHI PORTHARCOURT', 'JULUIS UMUKORO', '2347038590956', 'j.umukoro2019@gmail.com'],
  [162, 'KELCYN TRADING COMPANY LTD', '5 ALEX ROAD APAPA LAGOS', 'UDEMMADU KELECHI CYNTHIA', '2349035361273', 'info@kelcyntradingcompany.com'],
  [163, 'DON CLETUS INTERGRATED SERVICES LTD', 'SIKIRU NOLLA ST,OPP CARE LAND SCHOOL REMLEK AJAH LAGOS', 'EHIANU CLETUS', '2348062722818,2348077415210', 'doncletusintservices@gmail.com'],
  [164, 'LEBRADAN NIGERIA LIMITED', '1A/1B CROWTHER CRESCENT GRA APAPA', 'DANJUMA NASIRU IBRAHIM', '2347032038233,2348097531003', 'ibrodinho2007@gmail.com'],
  [165, 'HENRIETTA MARITIME NIG LTD', '23 ADELE ROAD APAPA', 'FIDELIS OSEGHALE EBOSELE', '2348057529322', 'henriettamaritime@yahoo.com'],
  [166, 'MFN PORT SERVICES LTD', '2A AZARE CRESCENT OFF LIVERPOOL ROAD APAPA', 'ANDY CHUKWUELOZONAM ISICHEI', '2348037193288', 'andy.isichei@mfnportervices.com.ng, operational@mfnportservices.com.ng'],
  [167, 'JOHNSONTIME INTEGRATED SERVICES LTD', '7 WARE HOUSE ROAD,APAPA LAGOS', 'DAYO JOHNSON', '2348080406999', 'johnsontime80@gmail.com'],
  [168, 'REINA CHAW INDUSTRIAL AND LOGISTIC SERVICES NIG LT', '33 CREEK ROAD IBRU GLASS HOUSE APAPA', 'EWARAMI JOY ANWULI', '2348038028454', 'info@reinachawils.com'],
  [169, 'BLESSEDSEAROCK INTERNATION LTD', 'BLOCK 4E COCONUT MARKET PLACE APAPA', 'UGOCHUKWU,CHRISTIAN RAPHAEL', '2348068856290,2347081214686', 'blessedsearockchristian@gmail.com'],
  [171, 'VIC-DON INTERNATIONALCOMPANY Limited', '4/5 TINCAN ISLAND EXPRESS WAY BY COCONUT BUS STOP APAPA LAGOS NIGERIA', 'OKEY VICTOR RAPHAEL', '2348061174942,2347089451526', 'okeyvictor@gmail.com'],
];

const members = rows
  .filter((r) => r[1])
  .map((r, i) => ({
    id: i + 1,
    company: r[1],
    address: r[2] || '',
    contact: r[3] || '',
    phone: r[4] || '',
    email: r[5] || '',
  }));

fs.writeFileSync('data/members.json', JSON.stringify({ members }, null, 2) + '\n');
console.log('Wrote', members.length, 'members');
